#import the random module
import random
#write a function to generate a random #
def guessNumber(x):
    randomNumber = random.randint(1,x)
#get a guess from the player
    guess = 0
    player = input("What is your name? ")
    while guess != randomNumber:
        playerGuess = int(input("What number is your guess? "))

#if the guess matches the random number generated by the system, tell the player they are correct. 
        if playerGuess == randomNumber:
            print(f"Correctomundo, {player}!")
            break
#if the guess does not match the random number, tell the player if their guess is too low or too high.
        elif playerGuess < randomNumber:
            print(f"{playerGuess} is too low. Guess again! ")
        else: 
            playerGuess > randomNumber
            print(f"{playerGuess} is too high. Guess again! ")
guessNumber(10)
